export const SHOW_LOGIN_FORM = "SHOW_LOGIN_FORM";
export const AUTHENTICATE = "AUTHENTICATE";
export const LOGIN_MESSAGE = "LOGIN_MESSAGE";
export const CLOSE_LOGIN = "CLOSE_LOGIN";
export const LOGOUT = "LOGOUT";
export const SHOW_PENDING_REQUESTS = "SHOW_PENDING_REQUESTS";
export const GET_PENDING_REQUESTS = "GET_PENDING_REQUESTS";
